import { TimelineProvider } from "@/app/timeline-context";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import type { Metadata } from "next";
import { ThemeProvider as NextJSThemeProvider } from "next-themes";
import { Quicksand, Roboto, Volkhov } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const quickSand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const volkhov = Volkhov({
  variable: "--font-volkhov",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "OptiPathway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} className="dark">
      <body
        className={`${quickSand.variable} ${volkhov.variable} ${roboto.variable} antialiased`}
      >
        <NextJSThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
                              <TooltipProvider>
            <TimelineProvider>
              <Navbar />
              <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
              <Footer />
            </TimelineProvider>
          </TooltipProvider>
        </NextJSThemeProvider>
      </body>
    </html>
  );
}
